### ISSUE TITLE
question : cmake with -DCMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by yichuan520030910320** [marius-team/marius#146]
Why does running marius_train result in a core dump when I set -DCMAKE_BUILD_TYPE=Debug during pip install . or cmake, but not in release mode?

**Comment by yichuan520030910320** [comment]
while use gdb it occurs problems here
Thread 1 "marius_train" received signal SIGSEGV, Segmentation fault.
0x000000000045a9b4 in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::intrusive_ptr(c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl> const&) ()
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-189.5.el8_6.x86_64 nvidia-driver-cuda-libs-535.54.03-1.el8.x86_64
(gdb) bt
#0  0x000000000045a9b4 in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::intrusive_ptr(c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl> const&) ()
#1  0x00007ffff759add8 in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>& c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::operator=<c10::TensorImpl, c10::UndefinedTensorImpl>(c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl> const&) & () from /home/yw8143/marius_artifact/build_debug/libmarius.so
#2  0x00007ffff7598b3f in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::operator=(c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl> const&) & ()
   from /home/yw8143/marius_artifact/build_debug/libmarius.so
#3  0x00007ffff7593468 in at::Tensor::operator=(at::TensorBase const&) & () from /home/yw8143/marius_artifact/build_debug/libmarius.so
#4  0x00007ffff75934d9 in at::Tensor::operator=(at::Tensor const&) & () from /home/yw8143/marius_artifact/build_debug/libmarius.so
#5  0x00007ffff7673bbe in LayeredNeighborSampler::getNeighbors(at::Tensor, int) () from /home/yw8143/marius_artifact/build_debug/libmarius.so
#6  0x00007ffff75f3f45 in DataLoader::nodeClassificationSample(Batch*, int) () from /home/yw8143/marius_artifact/build_debug/libmarius.so
#7  0x00007ffff75f2dd1 in DataLoader::getBatch(int) () from /home/yw8143/marius_artifact/build_debug/libmarius.so
#8  0x00007ffff7771ef6 in SynchronousTrainer::train(int) () from /home/yw8143/marius_artifact/build_debug/libmarius.so
#9  0x00000000004442b4 in marius(int, char**) ()
#10 0x000000000044486d in main ()
