### ISSUE TITLE
module 'marius' has no attribute 'marius_eval'

### ISSUE THREAD

**Issue by wiketool** [marius-team/marius#156]
When I followed the steps in the README file to compile, running marius_train reported an error
```
(marius-2023) embed@embed:~/Documents/marius-2023$ marius_eval
Bindings not installed
Traceback (most recent call last):
  File "/home/embed/anaconda3/envs/marius-2023/bin/marius_eval", line 8, in <module>
    sys.exit(main())
  File "/home/embed/anaconda3/envs/marius-2023/lib/python3.6/site-packages/marius/console_scripts/marius_eval.py", line 7, in main
    m.marius_eval(len(sys.argv), sys.argv)
AttributeError: module 'marius' has no attribute 'marius_eval'
```

**Comment by yichuan-w** [comment]
The same problem

**Comment by pranjalnam** [comment]
Were you able to find a solution to this?
