### ISSUE TITLE
Error when building an environment with docker

### ISSUE THREAD

**Issue by zzyuanyi** [marius-team/marius#159]
**Describe the bug**
Building wheels for collected packages: marius
  Building wheel for marius (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for marius (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
 subprocess.CalledProcessError: Command '['cmake', '/working_dir', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/working_dir/build/lib.linux-x86_64-3.10/marius', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE', '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE', '-DUSE_CUDA=TRUE', '-DUSE_OMP=TRUE', '-DCMAKE_INSTALL_RPATH=$ORIGIN']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for marius
Failed to build marius
ERROR: Could not build wheels for marius, which is required to install pyproject.toml-based projects

**To Reproduce**
1.CURRENT_DIR=`pwd`
2.git clone https://github.com/marius-team/marius.git
3.cd marius/examples/docker/
4.docker build -t marius:latest gpu_ubuntu/.
5.docker run --gpus all -it -v $CURRENT_DIR:/working_dir/ marius:latest bash
6.cd marius
7.pip3 install . --no-build-isolation
after the last step,the error happened
int order to down it I change the dockerfile FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 to FROM nvidia/cuda:11.8.0-base-ubuntu22.04
**Expected behavior**
build the marius correctly

**Environment**
List your operating system, and dependency versions. You can obtain this by running `marius_env_info` from the command line.

**Additional context**
Building wheels for collected packages: marius
  Building wheel for marius (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for marius (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing marius.egg-info/PKG-INFO
      writing dependency_links to marius.egg-info/dependency_links.txt
      writing entry points to marius.egg-info/entry_points.txt
      writing requirements to marius.egg-info/requires.txt
      writing top-level names to marius.egg-info/top_level.txt
      reading manifest file 'marius.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
      warning: no previously-included files matching '__pycache__' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.dylib' found anywhere in distribution
      warning: no previously-included files matching '.DS_Store' found anywhere in distribution
      warning: no previously-included files matching '*.gpickle' found anywhere in distribution
      adding license file 'LICENSE'
      writing manifest file 'marius.egg-info/SOURCES.txt'
      running build_ext
      CMake Error at /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/Internal/CMakeCUDAFindToolkit.cmake:104 (message):
        Failed to find nvcc.

        Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
        variable.
      Call Stack (most recent call first):
        /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:85 (cmake_cuda_find_toolkit)
        CMakeLists.txt:36 (enable_language)

      -- Configuring incomplete, errors occurred!
      ['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/working_dir/build/lib.linux-x86_64-3.10/marius', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE', '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE', '-DUSE_CUDA=TRUE', '-DUSE_OMP=TRUE', '-DCMAKE_INSTALL_RPATH=$ORIGIN']
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 81, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "setup.py", line 30, in run
          self.build_extension(ext)
        File "setup.py", line 72, in build_extension
          subprocess.check_call(["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/working_dir', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/working_dir/build/lib.linux-x86_64-3.10/marius', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE', '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE', '-DUSE_CUDA=TRUE', '-DUSE_OMP=TRUE', '-DCMAKE_INSTALL_RPATH=$ORIGIN']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for marius
Failed to build marius
ERROR: Could not build wheels for marius, which is required to install pyproject.toml-based projects

**Comment by zzyuanyi** [comment]
after another try ,I still meet the same problem when i use the nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
